el_client_name: erigon
el_image_name: thorax/erigon:docker_gwei
execution_endpoint: http://127.0.0.1:{{el_engine_snoop_port}}
snoop_command: "./json_rpc_snoop -p {{el_engine_snoop_port}} http://127.0.0.1:{{el_engine_port}}"

home_dir: "/home/{{ansible_user}}"

el_github_external_user_pubkeys:
  - Giulio2002
  - yperbasis

# bare websocket
elendpoint_ws: ws://127.0.0.1:8546

el_volumes:
  - "{{el_node_dir}}:/eldata"
  - "{{testnet_dir}}:/networkdata"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

geth_init_args: >
  erigon --datadir=/eldata init /networkdata/genesis.json

el_start_args: >
  erigon --datadir=/eldata
  --networkid={{chainID}}
  --http --http.api "eth,erigon,engine,debug,trace,txpool"
  --http.port {{el_rpc_port}}
  --http.addr 0.0.0.0
  --http.vhosts "*"
  --http.corsdomain "*"
  --ws
  --externalcl
  --authrpc.port={{el_engine_port}}
  --authrpc.addr=0.0.0.0
  --authrpc.jwtsecret=/jwtsecret
  --nat extip:{{ansible_host}}
  --allow-insecure-unlock
  --prune=htc
  --metrics --pprof --pprof.addr 0.0.0.0 --pprof.port={{el_metrics_port}}
  --batchSize=32m
  {% if (el_bootnode_enode is defined) and el_bootnode_enode %}
  --bootnodes="{{ el_bootnode_enode | join(',') }}"
  {% endif %}

#  --nodiscover
#  --staticpeers="{{ el_bootnode_enode | join(',') }}"

el_user_id: "1000:1000"