##############################################
# generic ansible config information
##############################################
ansible_user: "devops"
bootstrap_user: "devops"
initial_remote_user: "root"

github_user_pubkeys:
  - parithosh
  - ralexstokes
  - djrtwo
  - skylenet
  - samcm
  - barnabasbusa

ansible_python_interpreter: /usr/bin/python3
oh_my_zsh_config:
  PROMPT: "%{$fg[yellow]%}%n%{$fg[white]%}@%{$fg[red]%}%m%{$reset_color%} ${PROMPT}"

##############################################
# el endpoints
##############################################
# nimbus requires a websocket endpoint (http support unstable)
# note: also used for execution engine endpoint in nimbus
consensus_endpoint_nimbus: ws://127.0.0.1:8551

elendpoint: http://127.0.0.1:8545
beacon_api_endpoint: "http://127.0.0.1:{{beacon_api_port}}"


##############################################
# testnet specific information
##############################################
testnet_type: sepolia
cl_network_name: sepolia
deploy_mode: sync

chainID: 11155111
fee_recipient: "0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134"
# enter bootnodes here if needed
bootnode_enrs:
  - "enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk"

el_bootnode_enode:
  - "enode://ce970ad2e9daa9e14593de84a8b49da3d54ccfdf83cbc4fe519cb8b36b5918ed4eab087dedd4a62479b8d50756b492d5f762367c8d20329a7854ec01547568a6@165.22.196.173:30303"

##############################################
# metric information
##############################################
# enter pushgateway config if needed
prometheus_config_file: "prometheus/prometheus.yml.j2"
push_url: "https://victoriametrics.ethdevops.io/insert/0/prometheus/api/v1/write"
push_metrics_enabled: false
remote_write_auth: false
eth_metrics_exporter_enabled: false
eth_metrics_exporter_name: "metrics-exporter"
eth_metrics_exporter_image: "ethpandaops/ethereum-metrics-exporter:0.19.0"
remote_write_username: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/monitoring/observability-cluster/metrics-ingress-users/withdrawal-shadowfork-1.json | jq .username') }}"
remote_write_password: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/monitoring/observability-cluster/metrics-ingress-users/withdrawal-shadowfork-1.json | jq .password') }}"

no_validator_keys: false

##############################################
# ports to configure
##############################################
el_rpc_port: 8545
el_ws_rpc_port: 8546
el_engine_port_no_auth: 8550
el_engine_port: 8551
el_engine_snoop_port: 8560
el_engine_ws_port: 8552
nimbus_rpc_port: 4009
beacon_api_port: 4000
beacon_grpc_port: 4001
beacon_metrics_port: 8000
beacon_p2p_port: 9000
validator_metrics_port: 8001
validator_rpc_port: 4002
node_exporter_web_listen_address: "0.0.0.0:9100"
prometheus_web_listen_address: "0.0.0.0:9101"
el_metrics_port: 8002
eth_metrics_exporter_port: 8003

##############################################
# Command for JSON RPC snooper
##############################################
snoop_image_name: parithoshj/json_rpc_snoop:v1.0.0-x86
snoop_container_name: snooper

##############################################
# name of the validator to display
##############################################
graffiti: "{{cl_client_name}}-{{el_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"
# private dirs
# Validator assignments
local_validator_host_dir: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}"
local_validator_host_archive: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}.tar.gz"

##############################################
# remote host data directories
##############################################
home_dir: "/home/{{ansible_user}}"
beacon_node_dir: "{{home_dir}}/beacon"
validator_node_dir: "{{home_dir}}/validator"
testnet_dir: "{{home_dir}}/custom_config_data"
el_node_dir: "{{home_dir}}/eldata"

##############################################
# common log config
##############################################
beacon_log_level: info
common_log_options:
  max-file: "10"
  max-size: 500m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file

##############################################
# container names
##############################################
beacon_container_name: beacon
validator_container_name: validator
execution_container_name: execution
hi_peer_count: 100
separate_validator_process_enabled: true

firewall_allowed_tcp_ports:
  - 22
  - 30303
  - 9000

firewall_allowed_udp_ports:
  - 30303
  - 9000
firewall_additional_rules:
 - []
