- hosts: beaconchain_explorer
  become: true
  roles:
  # Docker. Required dependency
  - role: geerlingguy.docker
    tags: [docker]
  - role: geerlingguy.pip
    pip_install_packages:
    - name: docker
    - name: docker-compose
    tags: [docker]
  # Beaconchain explorer
  #- role: ethpandaops.general.beaconchain_explorer_aio
  - role: ../../../ansible-collection-general/roles/beaconchain_explorer_aio/
    tags: [beaconchain_explorer_aio]
